### ISSUE TITLE
Saving into a file, other than screenshot

### ISSUE THREAD

**Issue by sabinej** [andrea-cuttone/geoplotlib#5]
Is it possible to save the maps into a file automatically from the python code, instead of using the keyboard control "P" to save a screenshot?

**Comment by andrea-cuttone** [comment]
Hi 

you can use `geoplotlib.savefig('myfile')` instead of `geoplotlib.show()`

**Comment by sabinej** [comment]
Thanks a lot! It works, but it generates the messages below. That's not really a problem, but can I suppress this somehow?


%run C:/Users/sjeschonnek/Documents/Network_Research/geoplotlib_ex_flights.py
flightmap.png saved
Traceback (most recent call last):
  File "C:\Users\sjeschonnek\AppData\Local\Enthought\Canopy\User\lib\site-packages\geoplotlib-0.2.0-py2.7.egg\geoplotlib\__init__.py", line 30, in _runapp
    app.start()
  File "C:\Users\sjeschonnek\AppData\Local\Enthought\Canopy\User\lib\site-packages\geoplotlib-0.2.0-py2.7.egg\geoplotlib\core.py", line 311, in start
    pyglet.app.run()
  File "C:\Users\sjeschonnek\AppData\Local\Enthought\Canopy\User\lib\site-packages\pyglet-1.2.2-py2.7.egg\pyglet\app\__init__.py", line 143, in run
    event_loop.run()
  File "C:\Users\sjeschonnek\AppData\Local\Enthought\Canopy\User\lib\site-packages\pyglet-1.2.2-py2.7.egg\pyglet\app\base.py", line 136, in run
    self._run_estimated()
  File "C:\Users\sjeschonnek\AppData\Local\Enthought\Canopy\User\lib\site-packages\pyglet-1.2.2-py2.7.egg\pyglet\app\base.py", line 165, in _run_estimated
    timeout = self.idle()
  File "C:\Users\sjeschonnek\AppData\Local\Enthought\Canopy\User\lib\site-packages\pyglet-1.2.2-py2.7.egg\pyglet\app\base.py", line 281, in idle
    window.flip()
  File "C:\Users\sjeschonnek\AppData\Local\Enthought\Canopy\User\lib\site-packages\pyglet-1.2.2-py2.7.egg\pyglet\window\win32\__init__.py", line 309, in flip
    self.context.flip()
AttributeError: 'NoneType' object has no attribute 'flip'

**Comment by andrea-cuttone** [comment]
could you provide the minimal source code that produces this issue?

**Comment by sabinej** [comment]
"""
Example of spatial graph
"""
import geoplotlib
from geoplotlib.utils import read_csv
import pyglet


data = read_csv('./data/flights.csv')
geoplotlib.graph(data,
                 src_lat='lat_departure',
                 src_lon='lon_departure',
                 dest_lat='lat_arrival',
                 dest_lon='lon_arrival',
                 color='hot_r',
                 alpha=16,
                 linewidth=5)
#geoplotlib.show()
geoplotlib.savefig('flightmap4')

**Comment by sabinej** [comment]
The line with "import pyglet" can be removed, and it still happens. I was just trying out things. Thanks a lot for your help!

**Comment by andrea-cuttone** [comment]
should be fixed in 7b8620331b75eaec1c6c6f9d998fef525924257d

**Comment by sabinej** [comment]
Thanks, it works fine now!
